#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
RESET=$(tput sgr0)

echo
echo "${GREEN}In ChromeOS, make sure to go to ${BOLD}chrome://flags ${RESET}${GREEN}and enable ${BOLD}Crostini GPU${RESET}${GREEN} flag! ${RESET}"
echo

cleanup() {
    echo
    echo "${YELLOW}Exiting Crostini Vulkan setup...${RESET}"
    echo "${YELLOW}${BOLD}Please reboot Crostini to enable GPU acceleration. ${RESET}"
    echo
}
trap cleanup EXIT

read -rp "${CYAN}Enable GPU Acceleration for Crostini? ${BOLD}(y/N)${RESET}${CYAN}: ${RESET}" BUILD_CHOICE
case "$BUILD_CHOICE" in
    y|Y|yes|YES|Yes)
        echo
        echo "${GREEN}Proceeding to installation...${RESET}"
        sleep 1
        echo
        ;;
    *)
        echo
        echo "${RED}Exiting setup.${RESET}"
        sleep 2
        exit 0
        ;;
esac

sudo apt -o Acquire::ForceIPv4=true update
echo
echo "${BLUE}Adding ${BOLD}$USER${RESET}${BLUE} to groups to enable GPU acceleration: ${RESET}${CYAN}"
echo
getent group 44 || groupadd -g 44 video
sudo gpasswd -a $USER video
sudo gpasswd -a $USER render
sudo gpasswd -a $USER plugdev
echo "${RESET}"

DEBIAN_CODENAME="$(. /etc/os-release && echo "$VERSION_CODENAME")"
sudo tee /etc/apt/sources.list > /dev/null <<EOF
# Generated by distrobuilder
deb https://deb.debian.org/debian ${DEBIAN_CODENAME} main contrib non-free non-free-firmware
deb https://deb.debian.org/debian ${DEBIAN_CODENAME}-updates main contrib non-free non-free-firmware
deb https://deb.debian.org/debian-security ${DEBIAN_CODENAME}-security main contrib non-free non-free-firmware
deb-src https://deb.debian.org/debian ${DEBIAN_CODENAME} main contrib non-free non-free-firmware
EOF


if [ "$(uname -m)" != "aarch64" ]; then
    sudo dpkg --add-architecture i386
        if ! command -v steam >/dev/null 2>&1; then
        echo
        read -rp "${CYAN}Steam is not installed. Install Steam? ${BOLD}(y/N)${RESET}${CYAN}: ${RESET}" STEAM_CHOICE
        echo
    
        case "$STEAM_CHOICE" in
            y|Y|yes|YES|Yes)
                sudo apt -o Acquire::ForceIPv4=true update
                sudo apt install -y vulkan-tools mesa-utils vulkan-validationlayers steam-installer
                ;;
            *)
                echo
                echo "${YELLOW}Skipping Steam installation.${RESET}"
                echo
                ;;
        esac
    fi
fi



echo "${BLUE}"
sudo apt -o Acquire::ForceIPv4=true update
echo "${RESET}"
sudo apt install -y vulkan-tools mesa-utils vulkan-validationlayers

read -rp "${CYAN}Enable Swap in Crostini? ${BOLD}(y/N)${RESET}${CYAN}: ${RESET}" SWAP_CHOICE
        echo
    
        case "$SWAP_CHOICE" in
            y|Y|yes|YES|Yes)
                sudo curl -fsSL "https://raw.githubusercontent.com/shadowed1/Vulkini/main/crostini_swap_daemon.sh" -o "/bin/crostini_swap_daemon"
                sudo chmod +x "/bin/crostini_swap_daemon"
                crostini_swap_daemon startup
                crostini_swap_daemon
                ;;
            *)
                echo
                echo "${YELLOW}Skipping swap setup.${RESET}"
                echo
                ;;
        esac


sudo curl -fsSL "https://raw.githubusercontent.com/shadowed1/Chard/main/bin/gpu_test.sh" -o "/bin/gpu_test" 2>/dev/null
sleep 0.2
sudo chmod +x /bin/gpu_test 2>/dev/null
echo "${RED}${BOLD}Restart Linux VM and re-run ${RESET}${BOLD}${YELLOW}vulkan_tester${RESET}"
gpu_test 2>/dev/null
echo "${RED}${BOLD}Restart Linux VM and re-run ${RESET}${BOLD}${YELLOW}vulkan_tester${RESET}"



