#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
BOLD=$(tput bold)
RESET=$(tput sgr0)

echo
echo "${GREEN}In ChromeOS, make sure to go to ${BOLD}chrome://flags ${RESET}${GREEN}and enable ${BOLD}Crostini GPU${RESET}${GREEN} flag! ${RESET}"
echo

cleanup() {
    echo
    echo "${YELLOW}Exiting Crostini Vulkan setup...${RESET}"
}
trap cleanup EXIT

read -rp "${CYAN}Do you want to build Mesa + Vulkan for Crostini? ${BOLD}(y/N)${RESET}${CYAN}: ${RESET}" BUILD_CHOICE
case "$BUILD_CHOICE" in
    y|Y|yes|YES|Yes)
        echo
        echo "${GREEN}Proceeding to installation...${RESET}"
        sleep 1
        echo
        ;;
    *)
        echo
        echo "${RED}Exiting setup.${RESET}"
        sleep 2
        exit 0
        ;;
esac

sudo apt -o Acquire::ForceIPv4=true update
echo
echo "${BLUE}Adding ${BOLD}$USER${RESET}${BLUE} to groups to enable GPU acceleration: ${RESET}${CYAN}"
echo
getent group 44 || groupadd -g 44 video
sudo gpasswd -a $USER video
sudo gpasswd -a $USER render
sudo gpasswd -a $USER plugdev
echo "${RESET}"

DEBIAN_CODENAME="$(. /etc/os-release && echo "$VERSION_CODENAME")"
sudo tee /etc/apt/sources.list > /dev/null <<EOF
# Generated by distrobuilder
deb https://deb.debian.org/debian ${DEBIAN_CODENAME} main contrib non-free non-free-firmware
deb https://deb.debian.org/debian ${DEBIAN_CODENAME}-updates main contrib non-free non-free-firmware
deb https://deb.debian.org/debian-security ${DEBIAN_CODENAME}-security main contrib non-free non-free-firmware
deb-src https://deb.debian.org/debian ${DEBIAN_CODENAME} main contrib non-free non-free-firmware
EOF

if [ "$(uname -m)" != "aarch64" ]; then
    sudo dpkg --add-architecture i386
        if ! command -v steam >/dev/null 2>&1; then
        echo
        read -rp "${MAGENTA}Steam is not installed. Install Steam? (y/yes): ${RESET}" STEAM_CHOICE
        echo
    
        case "$STEAM_CHOICE" in
            y|Y|yes|YES|Yes)
                sudo apt install -y steam-installer
                ;;
            *)
                echo
                echo "${YELLOW}Skipping Steam installation.${RESET}"
                echo
                ;;
        esac
    fi
fi

sudo apt -o Acquire::ForceIPv4=true update
sudo apt install -y --no-upgrade --no-install-recommends vulkan-tools
sudo apt install -y --no-upgrade --no-install-recommends libepoxy-dev
sudo apt install -y --no-upgrade --no-install-recommends libvulkan-dev
sudo apt install -y --no-upgrade --no-install-recommends python3-yaml
sudo apt install -y --no-upgrade --no-install-recommends git
sudo apt install -y --no-upgrade --no-install-recommends meson
sudo apt install -y --no-upgrade --no-install-recommends pkg-config
sudo apt install -y --no-upgrade --no-install-recommends libvulkan-dev
sudo apt install -y --no-upgrade --no-install-recommends libclang-dev
sudo apt install -y --no-upgrade --no-install-recommends tar
sudo apt install -y --no-upgrade --no-install-recommends zstd
sudo apt install -y --no-upgrade --no-install-recommends mesa-utils
sudo apt install -y --no-upgrade --no-install-recommends cmake
sudo apt install -y --no-upgrade --no-install-recommends pkg-config
sudo apt install -y --no-upgrade --no-install-recommends lua5.4
sudo apt install -y --no-upgrade --no-install-recommends liblua5.4-dev
sudo apt install -y --no-upgrade --no-install-recommends vulkan-validationlayers
sudo apt install -y --no-upgrade --no-install-recommends libunwind-dev
sudo apt install -y --no-upgrade --no-install-recommends hwdata
sudo apt install -y --no-upgrade --no-install-recommends llvm
sudo apt install -y --no-upgrade --no-install-recommends llvm-dev
sudo apt install -y --no-upgrade --no-install-recommends clang
sudo apt install -y --no-upgrade --no-install-recommends libdisplay-info-dev
sudo apt install -y --no-upgrade --no-install-recommends valgrind
sudo apt install -y --no-upgrade --no-install-recommends libglvnd-dev
sudo apt install -y --no-upgrade --no-install-recommends glslang-tools
sudo apt install -y --no-upgrade --no-install-recommends libva-dev
sudo apt install -y --no-upgrade --no-install-recommends python3-mako
sudo apt install -y --no-upgrade --no-install-recommends zlib1g-dev
sudo apt install -y --no-upgrade --no-install-recommends libzstd-dev
sudo apt install -y --no-upgrade --no-install-recommends libexpat1-dev
sudo apt install -y --no-upgrade --no-install-recommends libdrm-dev
sudo apt install -y --no-upgrade --no-install-recommends byacc
sudo apt install -y --no-upgrade --no-install-recommends libudev-dev
sudo apt install -y --no-upgrade --no-install-recommends libelf-dev
sudo apt install -y --no-upgrade --no-install-recommends bison
sudo apt install -y --no-upgrade --no-install-recommends flex
sudo apt install -y --no-upgrade --no-install-recommends wayland-protocols
sudo apt install -y --no-upgrade --no-install-recommends libwayland-egl-backend-dev
sudo apt install -y --no-upgrade --no-install-recommends libxcb-randr0-dev
sudo apt install -y --no-upgrade --no-install-recommends libxext-dev
sudo apt install -y --no-upgrade --no-install-recommends libxcb-glx0-dev
sudo apt install -y --no-upgrade --no-install-recommends libxcb-shm0-dev
sudo apt install -y --no-upgrade --no-install-recommends libx11-xcb-dev
sudo apt install -y --no-upgrade --no-install-recommends libxcb-keysyms1-dev
sudo apt install -y --no-upgrade --no-install-recommends libxcb-dri3-dev
sudo apt install -y --no-upgrade --no-install-recommends libxcb-present-dev
sudo apt install -y --no-upgrade --no-install-recommends libxshmfence-dev
sudo apt install -y --no-upgrade --no-install-recommends libxxf86vm-dev
sudo apt install -y --no-upgrade --no-install-recommends libxrandr-dev
sudo apt install -y --no-upgrade --no-install-recommends libclc-19-dev
sudo apt install -y --no-upgrade --no-install-recommends llvm-19-dev 
sudo apt install -y --no-upgrade --no-install-recommends llvm-spirv-19
sudo apt install -y --no-upgrade --no-install-recommends libllvmspirvlib-19-dev
sudo apt install -y --no-upgrade --no-install-recommends clang-19 
sudo apt install -y --no-upgrade --no-install-recommends libclang-19-dev
sudo apt install -y --no-upgrade --no-install-recommends llvm-19-dev 
sudo apt install -y --no-upgrade --no-install-recommends llvm-spirv-19
#curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
sudo apt install -y --no-upgrade --no-install-recommends bindgen


# sudo apt -o Acquire::ForceIPv4=true upgrade -y

cd
rm -rf mesa-* 2>/dev/null
#LATEST=$(curl -s https://archive.mesa3d.org/ \
#  | grep -oE 'mesa-[0-9]+\.[0-9]+\.[0-9]+\.tar\.xz' \
#  | grep -v 'rc' \
#  | sort -V \
#  | tail -n1)
#wget "https://archive.mesa3d.org/$LATEST"
#tar xf "$LATEST"
#cd "${LATEST%.tar.xz}"
wget "https://archive.mesa3d.org/mesa-26.1.2.tar.xz"
tar xf "mesa-26.1.2.tar.xz"
cd mesa-26.1.2
ARCH="$(uname -m)"

case "$ARCH" in
    x86_64)
        LIBDIR="lib/x86_64-linux-gnu"

        # Removing specific GPU support
        CPU_VENDOR=$(grep -m1 "vendor_id" /proc/cpuinfo | awk -F: '{print $2}' | xargs)
        case "$CPU_VENDOR" in
            GenuineIntel)
                VULKAN_DRIVERS="virtio"
                INTEL_EXPERIMENTAL="true"
                INTEL_RT="enabled"
                # intel,virtio
                ;;
            AuthenticAMD)
                VULKAN_DRIVERS="virtio"
                INTEL_EXPERIMENTAL="false"
                INTEL_RT="disabled"
                # amd,virtio
                ;;
            *)
                echo "${YELLOW}Unknown x86 CPU vendor: $CPU_VENDOR. Defaulting to virtio.${RESET}"
                VULKAN_DRIVERS="virtio"
                INTEL_EXPERIMENTAL="false"
                INTEL_RT="disabled"
                ;;
        esac
        ;;
    aarch64)
        LIBDIR="lib/aarch64-linux-gnu"
        VULKAN_DRIVERS="virtio"
        INTEL_EXPERIMENTAL="false"
        INTEL_RT="disabled"
        ;;
    *)
        echo "${RED}Unsupported arch: $ARCH ${RESET}"
        sleep 5
        exit 1
        ;;
esac

rm -rf build 64 2>/dev/null
meson setup build64 \
    --libdir "$LIBDIR" \
    --wrap-mode=nofallback \
    -Dprefix=/usr \
    -Dgallium-d3d12-graphics=enabled \
    -Dplatforms=x11,wayland \
    -Dvulkan-drivers="$VULKAN_DRIVERS" \
    -Dintel-virtio-experimental="$INTEL_EXPERIMENTAL" \
    -Dintel-rt="$INTEL_RT" \
    -Dgallium-drivers=virgl,zink \
    -Dmesa-clc=enabled \
    -Dinstall-mesa-clc=true \
    -Dglx=dri \
    -Degl=enabled \
    -Dgbm=enabled \
    -Dgles1=enabled \
    -Dgles2=enabled \
    -Dspirv-tools=enabled \
    -Dgallium-rusticl=false \
    -Dvideo-codecs=all \
    -Dgallium-d3d12-video=enabled \
    -Dgallium-d3d12-graphics=enabled \
    -Dvalgrind=enabled
sudo ninja -C build64 install

ARCH="$(uname -m)"

if [ "$ARCH" = "x86_64" ]; then
    sudo cp build64/src/compiler/clc/mesa_clc /bin/ 2>/dev/null
    sudo cp build64/src/compiler/spirv/vtn_bindgen2 /bin/ 2>/dev/null
    sudo chmod +x /bin/mesa_clc 2>/dev/null
    sudo chmod +x /bin/vtn_bindgen2 2>/dev/null

    mkdir -p ~/.local/share/meson/cross

    cat > ~/.local/share/meson/cross/i686-cross.ini << 'EOF'
[binaries]
c = '/usr/bin/gcc'
cpp = '/usr/bin/g++'
ar = '/usr/bin/gcc-ar'
strip = '/usr/bin/strip'
pkg-config = '/usr/bin/i686-linux-gnu-pkg-config'
llvm-config = '/usr/bin/llvm-config'
cmake = '/usr/bin/cmake'

[built-in options]
c_args = ['-m32']
c_link_args = ['-m32']
cpp_args = ['-m32']
cpp_link_args = ['-m32']

[host_machine]
system = 'linux'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'
EOF

    sudo apt --fix-broken install -y
    sudo apt -o Acquire::ForceIPv4=true update
    sudo apt install -y --no-upgrade --no-install-recommends gcc-multilib
    sudo apt install -y --no-upgrade --no-install-recommends g++-multilib
    sudo apt install -y --no-upgrade --no-install-recommends pkg-config:i386
    sudo apt install -y --no-upgrade --no-install-recommends libdrm-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libwayland-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libwayland-egl-backend-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxext-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxfixes-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends x11proto-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-glx0-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-shm0-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libx11-xcb-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-dri2-0-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-dri3-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-present-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxshmfence-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxxf86vm-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxrandr-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libunwind-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libelf-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libzstd-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libbsd-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libsensors-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-keysyms1-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libva-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxshmfence-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libvulkan-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libglvnd-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libexpat1-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends zlib1g-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libx11-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-randr0-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-dri2-0-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxfixes-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb1-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-sync-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-xfixes0-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxdamage-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libxcb-dri3-dev:i386
    sudo apt install -y --no-upgrade --no-install-recommends libudev-dev:i386


    rm -rf build32 2>/dev/null
    meson setup build32 \
        --cross-file ~/.local/share/meson/cross/i686-cross.ini \
        --wrap-mode=nofallback \
        -Dprefix=/usr \
        -Dlibdir=lib/i386-linux-gnu \
        -Dplatforms=x11,wayland \
        -Dvulkan-drivers=virtio \
        -Dintel-virtio-experimental="$INTEL_EXPERIMENTAL" \
        -Dgallium-drivers=virgl,zink \
        -Dmesa-clc=enabled \
        -Dinstall-mesa-clc=true \
        -Dglx=dri \
        -Degl=enabled \
        -Dgbm=enabled \
        -Dgles1=enabled \
        -Dgles2=enabled \
        -Dllvm=disabled \
        -Dmesa-clc=system \
        -Dspirv-tools=disabled \
        -Dgallium-rusticl=false \
        -Dvideo-codecs=all \
        -Dgallium-d3d12-video=enabled \
        -Dgallium-d3d12-graphics=enabled \
        -Dvalgrind=disabled

    sudo ninja -C build32 install
    sudo rm /usr/share/drirc.d/00-mesa-defaults.conf 2>/dev/null
fi

rm -rf mesa-* 2>/dev/null
sudo apt --fix-broken install -y
echo

sudo curl -fsSL "https://raw.githubusercontent.com/shadowed1/Chard/main/bin/vulkan_tester.sh" -o "/bin/vulkan_tester" 2>/dev/null
sleep 0.2
sudo chmod +x /bin/vulkan_tester 2>/dev/null
vulkan_tester 2>/dev/null

echo "${RESET}"
