#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
BOLD=$(tput bold)
RESET=$(tput sgr0)
echo
echo "${GREEN}In ChromeOS, make sure to go to ${BOLD}chrome://flags ${RESET}${GREEN} and enable ${BOLD}Crostini GPU${RESET}${GREEN} flag! ${RESET}"
echo "${CYAN}Starting Vulkan install in 10 seconds... ${RESET}"
echo
sleep 8

sudo apt update

getent group 44 || groupadd -g 44 video
sudo gpasswd -a $USER video
sudo gpasswd -a $USER render
sudo gpasswd -a $USER plugdev

sudo tee /etc/apt/sources.list > /dev/null <<'EOF'
# Generated by distrobuilder
deb https://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
deb https://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
deb https://deb.debian.org/debian-security/ bookworm-security main main contrib non-free non-free-firmware
deb-src https://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
EOF

sudo apt upgrade -y
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install -y vulkan-tools
sudo apt install -y libepoxy-dev
sudo apt install -y libvulkan-dev
sudo apt install -y python3-yaml
sudo apt install -y git
sudo apt install -y meson
sudo apt install -y pkg-config
sudo apt install -y pkg-config libvulkan-dev
sudo apt install -y clang libclang-dev
sudo apt install -y zstd tar
sudo apt install -y mesa-utils
sudo apt install -y cmake
sudo apt install -y pkg-config cmake
sudo apt install -y lua5.4
sudo apt install -y liblua5.4-dev
sudo apt install -y vulkan-validationlayers
sudo apt install -y libunwind-dev
sudo apt install -y hwdata
sudo apt install -y llvm
sudo apt install -y llvm-dev
sudo apt install -y clang
sudo apt install -y libdisplay-info-dev
sudo apt install -y valgrind
sudo apt install -y libglvnd-dev
sudo apt install -y glslang-tools
sudo apt install -y libva-dev
sudo apt install -y python3-mako
sudo apt install -y zlib1g-dev
sudo apt install -y libzstd-dev
sudo apt install -y libexpat1-dev
sudo apt install -y libdrm-dev
sudo apt install -y byacc
sudo apt install -y libudev-dev
sudo apt install -y libelf-dev
sudo apt install -y bison
sudo apt install -y flex
sudo apt install -y wayland-protocols
sudo apt install -y libwayland-egl-backend-dev
sudo apt install -y libxcb-randr0-dev
sudo apt install -y libxext-dev
sudo apt install -y libxcb-glx0-dev
sudo apt install -y libxcb-shm0-dev
sudo apt install -y libx11-xcb-dev
sudo apt install -y libxcb-keysyms1-dev
sudo apt install -y libxcb-dri3-dev
sudo apt install -y libxcb-present-dev
sudo apt install -y libxshmfence-dev
sudo apt install -y libxxf86vm-dev
sudo apt install -y libxrandr-dev
sudo apt install -y libclc-19-dev
sudo apt install -y llvm-19-dev 
sudo apt install -y llvm-spirv-19
sudo apt install -y libllvmspirvlib-19-dev
sudo apt install -y clang-19 
sudo apt install -y libclang-19-dev
sudo apt install -y llvm-19-dev 
sudo apt install -y llvm-spirv-19

cd
rm -rf mesa-* 2>/dev/null
LATEST=$(curl -s https://archive.mesa3d.org/ \
  | grep -oE 'mesa-[0-9]+\.[0-9]+\.[0-9]+\.tar\.xz' \
  | grep -v 'rc' \
  | sort -V \
  | tail -n1)
wget "https://archive.mesa3d.org/$LATEST"
tar xf "$LATEST"
cd "${LATEST%.tar.xz}"

meson setup --reconfigure build64 \
    --libdir /usr/lib/x86_64-linux-gnu \
    --wrap-mode=nofallback \
    -Dprefix=/usr \
    -Dplatforms=x11,wayland \
    -Dvulkan-drivers=intel,virtio \
    -Dgallium-drivers=virgl,zink \
    -Dglx=dri \
    -Degl=enabled \
    -Dgbm=enabled \
    -Dgles1=enabled \
    -Dgles2=enabled \
    -Dspirv-tools=enabled \
    -Dgallium-rusticl=false \
    -Dvideo-codecs=all \
    -Dgallium-d3d12-video=enabled \
    -Dgallium-d3d12-graphics=enabled \
    -Dvalgrind=enabled

sudo ninja -C build64 install

sudo cp build64/src/compiler/clc/mesa_clc /bin/ 2>/dev/null
sudo cp build64/src/compiler/spirv/vtn_bindgen2 /bin/ 2>/dev/null
sudo chmod +x /bin/mesa_clc 2>/dev/null
sudo chmod +x /bin/vtn_bindgen2 2>/dev/null

mkdir -p ~/.local/share/meson/cross

    cat > ~/.local/share/meson/cross/i686-cross.ini << 'EOF'
[binaries]
c = '/usr/bin/gcc'
cpp = '/usr/bin/g++'
ar = '/usr/bin/gcc-ar'
strip = '/usr/bin/strip'
pkg-config = '/usr/bin/i686-linux-gnu-pkg-config'
llvm-config = '/usr/bin/llvm-config'
cmake = '/usr/bin/cmake'

[built-in options]
c_args = ['-m32']
c_link_args = ['-m32']
cpp_args = ['-m32']
cpp_link_args = ['-m32']

[host_machine]
system = 'linux'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'
EOF

sudo apt install -y gcc-multilib
sudo apt install -y g++-multilib
sudo apt install -y pkg-config:i386
sudo apt install -y libdrm-dev:i386
sudo apt install -y libwayland-dev:i386
sudo apt install -y libwayland-egl-backend-dev:i386
sudo apt install -y libxext-dev:i386
sudo apt install -y libxfixes-dev:i386
sudo apt install -y x11proto-dev:i386
sudo apt install -y libxcb-glx0-dev:i386
sudo apt install -y libxcb-shm0-dev:i386
sudo apt install -y libx11-xcb-dev:i386
sudo apt install -y libxcb-dri2-0-dev:i386
sudo apt install -y libxcb-dri3-dev:i386
sudo apt install -y libxcb-present-dev:i386
sudo apt install -y libxshmfence-dev:i386
sudo apt install -y libxxf86vm-dev:i386
sudo apt install -y libxrandr-dev:i386
sudo apt install -y libunwind-dev:i386
sudo apt install -y libelf-dev:i386
sudo apt install -y libzstd-dev:i386
sudo apt install -y libbsd-dev:i386
sudo apt install -y libsensors-dev:i386
sudo apt install -y libxcb-keysyms1-dev:i386
sudo apt install -y libva-dev:i386
sudo apt install -y libxshmfence-dev:i386
sudo apt install -y libvulkan-dev:i386
sudo apt install -y libglvnd-dev:i386
sudo apt install -y libexpat1-dev:i386
sudo apt install -y zlib1g-dev:i386
sudo apt install -y libx11-dev:i386
sudo apt install -y libxcb-randr0-dev:i386
sudo apt install -y libxcb-dri2-0-dev:i386
sudo apt install -y libxfixes-dev:i386
sudo apt install -y libxcb1-dev:i386
sudo apt install -y libxcb-sync-dev:i386
sudo apt install -y libxcb-xfixes0-dev:i386
sudo apt install -y libxdamage-dev:i386
sudo apt install -y libxcb-dri3-dev:i386

meson setup --reconfigure build32 \
    --cross-file ~/.local/share/meson/cross/i686-cross.ini \
    --wrap-mode=nofallback \
    -Dprefix=/usr \
    -Dlibdir=lib/i386-linux-gnu \
    -Dplatforms=x11,wayland \
    -Dvulkan-drivers=intel,virtio \
    -Dgallium-drivers=virgl,zink \
    -Dglx=dri \
    -Degl=enabled \
    -Dgbm=enabled \
    -Dgles1=enabled \
    -Dgles2=enabled \
    -Dllvm=disabled \
    -Dmesa-clc=system \
    -Dspirv-tools=disabled \
    -Dgallium-rusticl=false \
    -Dvideo-codecs=all \
    -Dgallium-d3d12-video=enabled \
    -Dgallium-d3d12-graphics=enabled \
    -Dvalgrind=disabled
    
sudo ninja -C build32 install

rm -rf mesa-* 2>/dev/null
vulkaninfo --summary
